version: "3.9"
services:
  spring-apps:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M
    ports:
      - 8080:8080
      - 8081:8081
